bump_version: null
lint:
  files_exist:
    - .github/workflows/linting_comment.yml
  files_unchanged:
    - .github/workflows/branch.yml
    - .github/workflows/linting.yml
nf_core_version: 3.0.2
org_path: null
repository_type: pipeline
template:
  author: "@maxulysse"
  description: help community build references
  force: false
  is_nfcore: true
  name: references
  org: nf-core
  outdir: .
  skip_features:
    - fastqc
    - igenomes
  version: 1.0dev
update: null
