lint:
  actions_awsfulltest: false
  files_exist:
    - conf/igenomes.config
    - conf/igenomes_ignored.config
  files_unchanged:
    - .github/PULL_REQUEST_TEMPLATE.md
    - .github/workflows/linting.yml
    - assets/nf-core-references_logo_light.png
    - docs/images/nf-core-references_logo_light.png
    - docs/images/nf-core-references_logo_dark.png
nf_core_version: 4.0.3
repository_type: pipeline
template:
  author: "@maxulysse"
  description: help community build references
  force: false
  is_nfcore: true
  name: references
  org: nf-core
  outdir: .
  skip_features:
    - fastqc
    - igenomes
  version: 0.2dev
